import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const mainPath = path.join(root, 'src', 'main.js');
const graphicsPath = path.join(root, 'src', 'modules', 'graphics-overhaul.js');
const cssPath = path.join(root, 'src', 'styles.css');
let main = fs.readFileSync(mainPath, 'utf8');
let graphics = fs.readFileSync(graphicsPath, 'utf8');
let css = fs.readFileSync(cssPath, 'utf8');

function replaceOnce(source, before, after, label) {
  const count = source.split(before).length - 1;
  if (count !== 1) throw new Error(`${label}: expected one match, found ${count}`);
  return source.replace(before, after);
}

function replaceBlock(source, startMarker, endMarker, replacement, label) {
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker, start);
  if (start < 0 || end < 0 || end <= start) throw new Error(`${label}: block markers not found`);
  return source.slice(0, start) + replacement + source.slice(end);
}

if (main.includes('NEON_BAY_V182_RUNTIME')) {
  console.log('Neon Bay v1.8.2 runtime patch already applied.');
  process.exit(0);
}

main = replaceOnce(
  main,
  "let v181RecoveryHint=null;",
  `let v181RecoveryHint=null;\n// NEON_BAY_V182_RUNTIME: low-allocation playability and collision broadphase.\nconst V182_COLLISION_CELL=24;\nconst v182CollisionGrid=new Map();\nlet v182CollisionStamp=0;\nconst v182DesiredMove=new THREE.Vector3();\nconst v182Displacement=new THREE.Vector3();\nconst v182CameraFocus=new THREE.Vector3();\nconst v182CameraDirection=new THREE.Vector3();\nconst v182CameraDesired=new THREE.Vector3();\nconst v182CameraProbe=new THREE.Vector3();\nlet v182CameraDistance=7;\nlet v182AIGate=0;\nlet v182InteractionGate=0;\nlet v182AdaptiveCooldown=0;`,
  'v1.8.2 runtime state'
);

const collisionBlock = `function v182GridKey(x,z){return x+','+z;}\n\nfunction v182IndexCollider(box){\n  const minCellX=Math.floor(box.minX/V182_COLLISION_CELL),maxCellX=Math.floor(box.maxX/V182_COLLISION_CELL);\n  const minCellZ=Math.floor(box.minZ/V182_COLLISION_CELL),maxCellZ=Math.floor(box.maxZ/V182_COLLISION_CELL);\n  box.v182Stamp=0;\n  for(let cx=minCellX;cx<=maxCellX;cx++)for(let cz=minCellZ;cz<=maxCellZ;cz++){\n    const key=v182GridKey(cx,cz);let bucket=v182CollisionGrid.get(key);\n    if(!bucket){bucket=[];v182CollisionGrid.set(key,bucket);}\n    bucket.push(box);\n  }\n}\n\nfunction addCollider(x, z, w, d, padding = .3) {\n  const box={ minX: x - w / 2 - padding, maxX: x + w / 2 + padding, minZ: z - d / 2 - padding, maxZ: z + d / 2 + padding };\n  collisionBoxes.push(box);v182IndexCollider(box);\n  const edge = 1.15;\n  coverPoints.push(\n    new THREE.Vector3(x-w/2-edge,0,z-d/2-edge), new THREE.Vector3(x+w/2+edge,0,z-d/2-edge),\n    new THREE.Vector3(x-w/2-edge,0,z+d/2+edge), new THREE.Vector3(x+w/2+edge,0,z+d/2+edge)\n  );\n}\n\nfunction collidesAt(x, z, radius = .55) {\n  const interiorCollision = interiorSystem?.collidesAt(x, z, radius);\n  if (interiorCollision !== null && interiorCollision !== undefined) return interiorCollision;\n  const onPier = x >= 150 - radius && x <= 206 + radius && z >= 117 - radius && z <= 133 + radius;\n  if (x < -176 + radius || ((!onPier) && x > 155 - radius) || z < -176 + radius || z > 176 - radius) return true;\n  const minCellX=Math.floor((x-radius)/V182_COLLISION_CELL),maxCellX=Math.floor((x+radius)/V182_COLLISION_CELL);\n  const minCellZ=Math.floor((z-radius)/V182_COLLISION_CELL),maxCellZ=Math.floor((z+radius)/V182_COLLISION_CELL);\n  const stamp=++v182CollisionStamp;\n  for(let cx=minCellX;cx<=maxCellX;cx++)for(let cz=minCellZ;cz<=maxCellZ;cz++){\n    const bucket=v182CollisionGrid.get(v182GridKey(cx,cz));if(!bucket)continue;\n    for(let i=0;i<bucket.length;i++){const box=bucket[i];if(box.v182Stamp===stamp)continue;box.v182Stamp=stamp;\n      if (x + radius > box.minX && x - radius < box.maxX && z + radius > box.minZ && z - radius < box.maxZ) return true;\n    }\n  }\n  return false;\n}\n\n`;
main = replaceBlock(main, 'function addCollider(', 'function createPlayer()', collisionBlock, 'collision broadphase');

const playerBlock = `function updatePlayer(dt) {\n  if (!player || state.activeVehicle || !state.running || state.paused || state.gameOver) return;\n  const forward=inputAxis('forward'),turn=inputAxis('turn');\n  const moving=Math.abs(forward)>.03||Math.abs(turn)>.03;\n  const sprint=(input.keys.has('ShiftLeft')||input.keys.has('ShiftRight'))&&state.stamina>2&&forward>.1;\n  const speed=sprint?CONFIG.sprintSpeed:CONFIG.playerSpeed;\n  if(sprint)state.stamina=Math.max(0,state.stamina-dt*24);else state.stamina=Math.min(100,state.stamina+dt*(moving?9:16));\n  const fwd=tmpV.set(-Math.sin(cameraYaw),0,-Math.cos(cameraYaw));\n  const right=tmpV2.set(Math.cos(cameraYaw),0,-Math.sin(cameraYaw));\n  v182DesiredMove.set(0,0,0).addScaledVector(fwd,forward).addScaledVector(right,turn);\n  if(v182DesiredMove.lengthSq()>1)v182DesiredMove.normalize();\n  v182DesiredMove.multiplyScalar(speed);\n  const response=moving?(sprint?10:13):18;\n  v181MoveVelocity.lerp(v182DesiredMove,1-Math.exp(-response*Math.min(dt,.05)));\n  v182Displacement.copy(v181MoveVelocity).multiplyScalar(dt);\n  const distance=Math.sqrt(v182Displacement.x*v182Displacement.x+v182Displacement.z*v182Displacement.z);\n  const steps=Math.max(1,Math.ceil(distance/.22));\n  const stepX=v182Displacement.x/steps,stepZ=v182Displacement.z/steps;\n  let moved=false;\n  for(let i=0;i<steps;i++){\n    const nx=player.position.x+stepX,nz=player.position.z+stepZ;\n    if(!collidesAt(nx,player.position.z,.44)){player.position.x=nx;moved=true;}else v181MoveVelocity.x*=.18;\n    if(!collidesAt(player.position.x,nz,.44)){player.position.z=nz;moved=true;}else v181MoveVelocity.z*=.18;\n  }\n  if(moved){player.rotation.y=rotateToward(player.rotation.y,Math.atan2(v181MoveVelocity.x,v181MoveVelocity.z),Math.min(1,dt*10));if(!collidesAt(player.position.x,player.position.z,.5))v181LastSafePosition.copy(player.position);}\n  if((input.jumpQueued||input.keys.has('Space'))&&player.position.y<=.001){playerVelocity.y=CONFIG.jumpVelocity;audio.tone(180,.08,'triangle',.06,80);}\n  input.jumpQueued=false;\n  playerVelocity.y-=CONFIG.gravity*dt;\n  player.position.y+=playerVelocity.y*dt;\n  if(player.position.y<0){player.position.y=0;playerVelocity.y=0;}\n  const desiredAnimation = player.position.y > .08 ? 'Run' : sprint ? 'Run' : moving ? 'Walk' : (input.aim ? 'Aim' : 'Idle');\n  playerActor?.setWeapon(state.weapon);\n  playerActor?.update(dt, desiredAnimation);\n}\n\n`;
main = replaceBlock(main, 'function updatePlayer(dt) {', 'function inputAxis(kind)', playerBlock, 'player movement');

const cameraBlock = `function updateCamera(dt) {\n  if(!player||!camera)return;\n  const target=state.activeVehicle?state.activeVehicle.mesh.position:player.position;\n  const height=state.activeVehicle?2.4:1.65;\n  const baseDistance=state.activeVehicle?10.5:cameraDistance;\n  v182CameraFocus.set(target.x,target.y+height,target.z);\n  v182CameraDirection.set(Math.sin(cameraYaw)*Math.cos(cameraPitch),-Math.sin(cameraPitch),Math.cos(cameraYaw)*Math.cos(cameraPitch));\n  let safeDistance=baseDistance;\n  const samples=8;\n  for(let i=1;i<=samples;i++){const d=1.15+(baseDistance-1.15)*(i/samples);v182CameraProbe.copy(v182CameraFocus).addScaledVector(v182CameraDirection,d);if(collidesAt(v182CameraProbe.x,v182CameraProbe.z,.24)){safeDistance=Math.max(1.1,d-(baseDistance/samples));break;}}\n  const response=safeDistance<v182CameraDistance?18:7;\n  v182CameraDistance=lerp(v182CameraDistance,safeDistance,1-Math.exp(-response*dt));\n  v182CameraDesired.copy(v182CameraFocus).addScaledVector(v182CameraDirection,v182CameraDistance);\n  camera.position.lerp(v182CameraDesired,1-Math.exp(-11*dt));\n  const speed=Math.abs(state.activeVehicle?.speed||0);\n  const targetFov=state.activeVehicle?clamp(62+speed*.2,62,74):input.aim?53:64;\n  const nextFov=lerp(camera.fov,targetFov,1-Math.exp(-6*dt));\n  if(Math.abs(nextFov-camera.fov)>.01){camera.fov=nextFov;camera.updateProjectionMatrix();}\n  camera.lookAt(v182CameraFocus);\n}\n\nfunction updateAI(dt) {\n  const p=getPlayerPosition();\n  const enemyPhase=Math.floor(worldTime*10)&1,vehiclePhase=Math.floor(worldTime*7)&1;\n  for(let i=0;i<enemies.length;i++){const e=enemies[i],distanceSq=e.group.position.distanceToSquared(p);if(distanceSq<13225||(i&1)===enemyPhase)e.update(dt);}\n  const stride=state.quality==='low'?5:state.quality==='medium'?4:3,phase=Math.floor(worldTime*8)%stride;\n  for(let i=0;i<pedestrians.length;i++){const e=pedestrians[i],distanceSq=e.group.position.distanceToSquared(p);if(distanceSq<2304||i%stride===phase)e.update(dt);}\n  for(let i=0;i<vehicles.length;i++){const v=vehicles[i],distanceSq=v.mesh.position.distanceToSquared(p);if(v===state.activeVehicle||v.type==='police'||distanceSq<15625||(i&1)===vehiclePhase)v.update(dt);}\n}\n\n`;
main = replaceBlock(main, 'function updateCamera(dt) {', 'function updateWanted(dt)', cameraBlock, 'camera and AI');

const interactionBlock = `function updateInteractions() {\n  if(!state.running||state.paused){dom.interaction.classList.add('hidden');input.interactQueued=false;return;}\n  const p=getPlayerPosition();\n  let candidate=null,distSq=Infinity;\n  if(state.activeVehicle){candidate={type:'exit',label:'Exit vehicle',object:state.activeVehicle};distSq=0;}\n  else {\n    for(let i=0;i<vehicles.length;i++){const v=vehicles[i];if(v.ai||v.destroyed)continue;const dSq=p.distanceToSquared(v.mesh.position);if(dSq<9.61&&dSq<distSq){candidate={type:'vehicle',label:\`Enter \${vehicleDisplayName(v)}\`,object:v};distSq=dSq;}}\n    for(let i=0;i<interactables.length;i++){const item=interactables[i];const allowed=!item.interiorOnly||state.currentInterior===item.interiorOnly;if(item.marker)item.marker.visible=allowed;if(!allowed)continue;const dSq=p.distanceToSquared(item.position),radiusSq=item.radius*item.radius;if(dSq<radiusSq&&dSq<distSq){candidate={type:item.type,label:item.label,object:item};distSq=dSq;}}\n  }\n  const previous=dom.interaction._candidate;\n  if(candidate){dom.interaction.classList.remove('hidden');if(!previous||previous.type!==candidate.type||previous.object!==candidate.object)dom.interactionText.textContent=candidate.label;dom.interaction.dataset.type=candidate.type;dom.interaction._candidate=candidate;}\n  else{dom.interaction.classList.add('hidden');dom.interaction._candidate=null;}\n  if(input.interactQueued){input.interactQueued=false;if(candidate)performInteraction(candidate);}\n}\n\n`;
main = replaceBlock(main, 'function updateInteractions() {', 'function performInteraction(candidate)', interactionBlock, 'interaction scan');

const polishBlock = `function buildV181WorldPolish(){\n  const matrix=new THREE.Matrix4();\n  const markGeo=new THREE.BoxGeometry(.16,.018,4.8);\n  const roadMat=new THREE.MeshStandardMaterial({color:0xf5f0d6,roughness:.72,metalness:.02,emissive:0x18150b,emissiveIntensity:.12});\n  const marks=[];for(let z=-156;z<=156;z+=12)for(const x of [-120,-60,0,60,120])marks.push([x,z]);\n  const markMesh=new THREE.InstancedMesh(markGeo,roadMat,marks.length);\n  marks.forEach(([x,z],i)=>{matrix.makeTranslation(x,.035,z);markMesh.setMatrixAt(i,matrix);});markMesh.instanceMatrix.needsUpdate=true;markMesh.receiveShadow=true;scene.add(markMesh);\n  const trunkGeo=new THREE.CylinderGeometry(.18,.26,2.5,7),crownGeo=new THREE.IcosahedronGeometry(1.25,0);\n  const trunkMat=new THREE.MeshStandardMaterial({color:0x68452e,roughness:.95}),leafMat=new THREE.MeshStandardMaterial({color:0x1f6a48,roughness:.82});\n  const positions=[];for(let i=0;i<28;i++){const a=i*2.399,r=148+(i%3)*7,x=Math.cos(a)*r,z=Math.sin(a)*r;if(!collidesAt(x,z,1.5))positions.push([x,z]);}\n  const trunks=new THREE.InstancedMesh(trunkGeo,trunkMat,positions.length),crowns=new THREE.InstancedMesh(crownGeo,leafMat,positions.length);\n  positions.forEach(([x,z],i)=>{matrix.makeTranslation(x,1.25,z);trunks.setMatrixAt(i,matrix);matrix.makeTranslation(x,3,z);crowns.setMatrixAt(i,matrix);});\n  trunks.instanceMatrix.needsUpdate=true;crowns.instanceMatrix.needsUpdate=true;trunks.castShadow=crowns.castShadow=state.quality==='high'||state.quality==='ultra';trunks.receiveShadow=crowns.receiveShadow=true;scene.add(trunks,crowns);\n}\n\n`;
main = replaceBlock(main, 'function buildV181WorldPolish(){', 'function beginPlay() {', polishBlock, 'instanced world polish');

const animateBlock = `function animate(now = performance.now()) {\n  requestAnimationFrame(animate);\n  if (!renderer || !scene || document.hidden) return;\n  const activelyPlaying = state.running && !state.paused && !state.gameOver && !state.cinematic;\n  const targetFps = activelyPlaying ? (state.quality === 'low' ? 40 : state.quality === 'medium' ? 55 : 60) : 20;\n  if (now - frameGate < 1000 / targetFps) return;\n  frameGate = now;\n\n  const dt = Math.min(clock.getDelta(), .05);\n  minimapGate += dt;hudGate += dt;v182AIGate += dt;v182InteractionGate += dt;v182AdaptiveCooldown=Math.max(0,v182AdaptiveCooldown-dt);\n  const redrawMinimap = minimapGate >= .12;\n  const refreshHud = hudGate >= .1;\n  if (redrawMinimap) minimapGate = 0;\n  if (refreshHud) hudGate = 0;\n\n  const slowLimit=state.quality==='low'?.046:state.quality==='medium'?.032:.027;\n  if (activelyPlaying && dt > slowLimit) slowFrameBudget += dt;\n  else slowFrameBudget = Math.max(0, slowFrameBudget - dt * 1.15);\n  if (slowFrameBudget > 1.35 && v182AdaptiveCooldown<=0 && state.quality !== 'low') {\n    applyQuality(state.quality === 'ultra' ? 'high' : state.quality === 'high' ? 'medium' : 'low');\n    notify('Graphics reduced to keep gameplay responsive.', 2.4);\n    slowFrameBudget = 0;v182AdaptiveCooldown=10;\n  }\n\n  if(state.demoMode&&demoDirector){\n    demoDirector.update(dt,{camera,player,playerActor,vehicles,enemies,state,enterDemoInterior,exitDemoInterior});\n    vehicles.forEach(v=>v.update(dt));pedestrians.forEach(p=>p.actor?.update(dt,'Walk'));updateWorld(dt);if(redrawMinimap)drawMinimap();\n  } else if(state.cinematic){\n    updateCinematic(dt);updateWorld(dt);updateNotification(dt);if(redrawMinimap)drawMinimap();\n  } else if(activelyPlaying){\n    dialogue?.update(dt);updatePlayer(dt);\n    const aiInterval=state.quality==='low'?.05:1/30;if(v182AIGate>=aiInterval){const aiDt=Math.min(v182AIGate,.08);v182AIGate=0;updateAI(aiDt);}\n    updateCamera(dt);updateMission(dt);updateSideActivity(dt);updateWanted(dt);updateWorld(dt);\n    if(v182InteractionGate>=.1||input.interactQueued){v182InteractionGate=0;updateInteractions();}\n    updateNotification(dt);if(refreshHud)updateHUD();if(redrawMinimap)drawMinimap();\n    if(input.fire)shoot();saveTimer+=dt;if(saveTimer>30){saveTimer=0;saveGame(true);}\n  } else if(scene){dialogue?.update(dt);updateCamera(dt);updateWorld(dt*.18);updateNotification(dt);if(redrawMinimap)drawMinimap();}\n  const useComposer = composer && (state.quality === 'high' || state.quality === 'ultra');\n  if(useComposer)composer.render();else renderer.render(scene,camera);\n}\n\n`;
main = replaceBlock(main, 'function animate(now = performance.now()) {', 'function startDemoMode()', animateBlock, 'adaptive frame loop');

main = main.replaceAll('v1.8.1', 'v1.8.2');

graphics = replaceOnce(graphics,
  '    this.dustOrigin = new THREE.Vector3();',
  '    this.dustOrigin = new THREE.Vector3();\n    this.tmpA = new THREE.Vector3();\n    this.tmpB = new THREE.Vector3();\n    this.tmpC = new THREE.Vector3();',
  'graphics scratch vectors');
graphics = replaceOnce(graphics,
  `      this.fillLight.position.lerp(new THREE.Vector3(target.x - 3, target.y + 7, target.z + 3), clamp(dt * 5, 0, 1));\n      this.rimLight.position.lerp(new THREE.Vector3(target.x + 2, target.y + 3, target.z - 2), clamp(dt * 7, 0, 1));`,
  `      this.fillLight.position.lerp(this.tmpA.set(target.x - 3, target.y + 7, target.z + 3), clamp(dt * 5, 0, 1));\n      this.rimLight.position.lerp(this.tmpB.set(target.x + 2, target.y + 3, target.z - 2), clamp(dt * 7, 0, 1));`,
  'graphics light allocation');
graphics = replaceOnce(graphics,
  `      const forward = new THREE.Vector3(-Math.sin(vehicle.rotation), 0, -Math.cos(vehicle.rotation));\n      const right = new THREE.Vector3(Math.cos(vehicle.rotation), 0, -Math.sin(vehicle.rotation));\n      this.headlight.position.copy(vehicle.mesh.position).addScaledVector(forward, 1.7).add(new THREE.Vector3(0, 1, 0));\n      this.headlight.target.position.copy(vehicle.mesh.position).addScaledVector(forward, 24).addScaledVector(right, vehicle.steerAngle * 4).add(new THREE.Vector3(0, .25, 0));`,
  `      const forward = this.tmpA.set(-Math.sin(vehicle.rotation), 0, -Math.cos(vehicle.rotation));\n      const right = this.tmpB.set(Math.cos(vehicle.rotation), 0, -Math.sin(vehicle.rotation));\n      this.headlight.position.copy(vehicle.mesh.position).addScaledVector(forward, 1.7).add(this.tmpC.set(0, 1, 0));\n      this.headlight.target.position.copy(vehicle.mesh.position).addScaledVector(forward, 24).addScaledVector(right, vehicle.steerAngle * 4).add(this.tmpC.set(0, .25, 0));`,
  'graphics headlight allocation');

css = css.replaceAll('v1.8.1', 'v1.8.2');
fs.writeFileSync(mainPath, main);
fs.writeFileSync(graphicsPath, graphics);
fs.writeFileSync(cssPath, css);
console.log('Applied Neon Bay v1.8.2 playability and performance patch.');
